export const BEGIN_FETCH_CALL = 'BEGIN_FETCH_CALL';

export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILURE = 'AUTH_FAILURE';

export const REQUESTS_ALL_REQUEST = 'REQUESTS_ALL_REQUEST';
export const REQUESTS_ALL_SUCCESS = 'REQUESTS_ALL_SUCCESS';
export const REQUESTS_ALL_FAILURE = 'REQUESTS_ALL_FAILURE';

export const REQUESTS_USER_REQUEST = 'REQUESTS_USER_REQUEST';
export const REQUESTS_USER_SUCCESS = 'REQUESTS_USER_SUCCESS';
export const REQUESTS_USER_FAILURE = 'REQUESTS_USER_FAILURE';

export const REQUEST_FORM_VIEW = 'REQUEST_FORM_VIEW';
export const REQUEST_FORM_NEW = 'REQUEST_FORM_NEW';
