export const LOAD_RECORDS_SUCCESS = 'LOAD_RECORDS_SUCCESS';
export const CREATE_RECORD_SUCCESS = 'CREATE_RECORD_SUCCESS';
export const BEGIN_FETCH_CALL = 'BEGIN_FETCH_CALL';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const QUOTE_REQUEST = 'QUOTE_REQUEST';
export const QUOTE_SUCCESS = 'QUOTE_SUCCESS';
export const QUOTE_FAILURE = 'QUOTE_FAILURE';

export const FORM_VIEW = 'FORM_VIEW';
