/**
 * BARS key map
 */
exports.KEYS = {
    FORM_ID = 'id',
    FORM_STATUS = 'requestState',
    FORM_NAME = 'fullName',
    FORM_PHONE = 'workPhoneNumber',
    FORM_CELL = 'cellPhoneNumber',
    FORM_EMAIL = 'receiverEmail',
    FORM_LICENSE = 'licensePlate',
    FORM_COMPANY = 'companyName',
    FORM_COMPANY_ADDRESS = 'companyAddress',
    FORM_SUP_NAME = 'supervisorFullName',
    FORM_SUP_EMAIL = 'supervisorEmail',
    FORM_SUP_PHONE = 'supervisorPhoneNumber',
    FORM_DIVISION = 'division',
    FORM_UNIT = 'unitOrProject',
    FORM_REQUEST_DATE = 'CreatedDateUtc',
    FORM_AREAS = 'accessAreas',
    FORM_HOURS = 'accessHours',
    FORM_LEVELS = 'accessLevels',
    FORM_AREA_OTHER = 'accessOtherArea',
    FORM_REASON = 'accessReason',
    FORM_VENDOR_START = 'VendorStartDateUtc',
    FORM_KEYCARD = 'keycard',
    FORM_ISSUE = 'issueDateUtc',
    FORM_EXPIRE_DATE = 'expirationDateUtc',
    FORM_APPROVAL_DATE_SUP = 'supervisorApprovalTimestampUtc',
    FORM_APPROVAL_DATE_REC = 'receiverAgreementTimestampUtc',
    FORM_APPROVAL_DATE_SEC = 'securityApprovalTimestampUtc',
    FORM_SECURITY_NAME = 'securityApproverName',
    FORM_SECURITY_TIME = 'securityApprovalTimestampUtc',
    FORM_TERMS = 'receiverAgreementTimestampUtc',
    FORM_TERMS_SUP = 'supervisorApprovalTimestampUtc',
    FORM_SAM_SUBMIT = 'submitterSamAccount',
    FORM_SAM_RECEIVE = 'receiverSamAccount',
    FORM_SAM_SUPER = 'supervisorSamAccount',
    FORM_SUBMIT_EMAIL = 'submitterEmail',
    FORM_REJECT_REASON = 'cancellationReason',
    JUSTIFICATIONS_OTHER = 'justification_other_area',

    STATUS_ERROR = 0,
    STATUS_PEND_MGR = 1,
    STATUS_PEND_REC = 2,
    STATUS_PEND_SEC = 3,
    STATUS_APPROVED = 4,
    STATUS_CANCEL_MGR = 5,
    STATUS_CANCEL_SEC = 6,
    STATUS_CANCEL_REC = 7,
    STATUS_CANCEL_SUB = 8
};
